name: haskell-step
version: 0.1.0.0
github: aztecrex/haskell-step
license: BSD3
author: Greg Wiley
maintainer: aztec.rex@jammm.com
copyright: Greg Wiley

extra-source-files:
- README.md

description:  See GitHub <https://github.com/aztecrex/haskell-step#readme>

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src

executables:
  haskell-step-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-step

tests:
  haskell-step-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-step

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - MonoLocalBinds
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - InstanceSigs
